### PR TITLE
Add C++ GitHub Actions CI

### PR DESCRIPTION
**Pull request by jonpas**
Adds GitHub Actions as replacement to Travis CI.
- Builds all 4 types of builds that Travis did
  - "Executable" is kind of redundant as "Executable with Template" builds them both?
- Uploads Artifacts of every build type
- Runs on Linux and Windows
  - Installs newer CMake version on Linux (Windows already ships with up-to-date one)
- ~~Removes `.travis.yml`~~ Kept for template purposes

### CODE REVIEW

**Comment by NouberNou** [comment]
Do we also wanna get rid of the jenkins job?

**Comment by jonpas** [comment]
Depends if we want to keep it as part of the template or only use CI jobs for template testing itself. If former, I would leave all 3 actually, if latter then just Actions.

**Comment by NouberNou** [comment]
I think keeping it is fine.

**Comment by jonpas** [comment]
I will re-add Travis then as well.

> "Executable" is kind of redundant as "Executable with Template" builds them both?

What about this?

**Pull request merged**
